-- SkillTrack Assessment 3 - Supabase / PostgreSQL schema
-- Run this entire script in Supabase Dashboard -> SQL Editor.
-- It creates the application tables used by the Express REST API.

create extension if not exists pgcrypto;

-- Clean rebuild for a development database.
drop table if exists certificates cascade;
drop table if exists user_achievements cascade;
drop table if exists achievements cascade;
drop table if exists quiz_results cascade;
drop table if exists quiz_questions cascade;
drop table if exists quizzes cascade;
drop table if exists lesson_progress cascade;
drop table if exists enrollments cascade;
drop table if exists lessons cascade;
drop table if exists courses cascade;
drop table if exists users cascade;

create table users (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(255) not null unique,
  password varchar(255) not null,
  role varchar(20) not null default 'student' check (role in ('student','admin')),
  goal varchar(255) not null default 'Become a confident frontend developer',
  avatar varchar(500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table courses (
  id bigint generated by default as identity primary key,
  title varchar(200) not null,
  description text not null,
  category varchar(100) not null,
  instructor varchar(150) not null,
  level varchar(30) not null default 'Beginner' check (level in ('Beginner','Intermediate','Advanced')),
  duration varchar(50),
  rating numeric(3,2) not null default 0,
  image_url varchar(500),
  skills jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table lessons (
  id bigint generated by default as identity primary key,
  course_id bigint not null references courses(id) on delete cascade,
  title varchar(200) not null,
  description text,
  content text,
  lesson_order integer not null default 1,
  duration_minutes integer,
  created_at timestamptz not null default now()
);
create index idx_lessons_course on lessons(course_id);

create table enrollments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  course_id bigint not null references courses(id) on delete cascade,
  progress numeric(5,2) not null default 0,
  completed boolean not null default false,
  enrolled_at timestamptz not null default now(),
  completed_at timestamptz,
  unique(user_id, course_id)
);
create index idx_enrollments_user on enrollments(user_id);
create index idx_enrollments_course on enrollments(course_id);

create table lesson_progress (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  lesson_id bigint not null references lessons(id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  unique(user_id, lesson_id)
);
create index idx_progress_user on lesson_progress(user_id);
create index idx_progress_lesson on lesson_progress(lesson_id);

create table quizzes (
  id bigint generated by default as identity primary key,
  course_id bigint not null unique references courses(id) on delete cascade,
  title varchar(200) not null,
  description text,
  passing_score numeric(5,2) not null default 70,
  created_at timestamptz not null default now()
);

create table quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references quizzes(id) on delete cascade,
  question text not null,
  option_a varchar(500) not null,
  option_b varchar(500) not null,
  option_c varchar(500),
  option_d varchar(500),
  correct_option varchar(1) not null check (correct_option in ('A','B','C','D')),
  question_order integer not null default 1
);
create index idx_questions_quiz on quiz_questions(quiz_id);

create table quiz_results (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  quiz_id bigint not null references quizzes(id) on delete cascade,
  score numeric(5,2) not null,
  passed boolean not null default false,
  attempted_at timestamptz not null default now()
);
create index idx_results_user on quiz_results(user_id);
create index idx_results_quiz on quiz_results(quiz_id);

create table achievements (
  id bigint generated by default as identity primary key,
  name varchar(150) not null unique,
  description text not null,
  icon varchar(500),
  requirement varchar(255),
  created_at timestamptz not null default now()
);

create table user_achievements (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  achievement_id bigint not null references achievements(id) on delete cascade,
  awarded_at timestamptz not null default now(),
  unique(user_id, achievement_id)
);

create table certificates (
  id bigint generated by default as identity primary key,
  certificate_code varchar(100) not null unique,
  user_id bigint not null references users(id) on delete cascade,
  course_id bigint not null references courses(id) on delete cascade,
  issued_at timestamptz not null default now(),
  unique(user_id, course_id)
);
create index idx_certificates_user on certificates(user_id);
create index idx_certificates_course on certificates(course_id);

-- updated_at helper for tables that expose it.
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_updated_at on users;
create trigger users_updated_at before update on users for each row execute function set_updated_at();
drop trigger if exists courses_updated_at on courses;
create trigger courses_updated_at before update on courses for each row execute function set_updated_at();

-- Used by the seed script after inserting the existing numeric course IDs.
create or replace function set_course_sequence(next_value bigint)
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('courses','id'), greatest(next_value - 1, 1), true);
end;
$$;

-- Development seed data.
insert into achievements (name, description, icon, requirement) values
('First Enrolment', 'Enrol in your first course.', '🎓', 'Complete your first enrolment'),
('First Lesson', 'Complete your first lesson.', '📚', 'Complete one lesson'),
('Quiz Starter', 'Complete your first quiz.', '📝', 'Submit one quiz'),
('Course Completed', 'Complete an entire course.', '🏆', 'Reach 100% course progress'),
('Learning Streak', 'Maintain a learning streak.', '🔥', 'Complete learning activity on consecutive days');

-- The course catalogue, lessons and quizzes are loaded by: npm run seed
